//#include,"common.h"

enum {
	LNOT,
	MOD,
	LAND,
	LP,
	RP,
	MULT,
	ADD,
	COMMA,
	SUB,
	DOT,
	DIV,
	COLON,
	SEMI,
	LT,
	ASSIGN,
	GT,
	QOP,
	LB,
	RB,
	XOR,
	LC,
	LOR,
	RC,
	NOT,
	ID,
	NUM,
	STRING,
	LITERAL,
	SIZEOF,
	PTR,
	INC,
	DEC,
	LSHIFT,
	RSHIFT,
	LE,
	GE,
	EQ,
	NE,
	AND,
	OR,
	MULE,
	DIVE,
	MODE,
	ADDE,
	SUBE,
	LSHIFTE,
	RSHIFTE,
	ANDE,
	XORE,
	ORE,
	TYPE_NAME,
	TYPEDEF,
	EXTERN,
	STATIC,
	AUTO,
	REGISTER,
	CHAR,
	SHORT,
	INT,
	LONG,
	SIGNED,
	UNSIGNED,
	FLOAT,
	DOUBLE,
	CONST,
	VOLATILE,
	VOID,
	STRUCT,
	UNION,
	ENUM,
	ELLIPSIS,
	CASE,
	DEFAULT,
	IF,
	ELSE,
	SWITCH,
	WHILE,
	DO,
	FOR,
	GOTO,
	CONTINUE,
	BREAK,
	RETURN,

	SPLIT_TERMINAL_UNTERMINAL,

	PriExp,
	PostExp,
	ArgExpList,
	UnaryExp,
	UnaryOp,
	CastExp,
	MulExp,
	AddExp,
	ShiftExp,
	RelExp,
	EquExp,
	AndExp,
	XorExp,
	OrExp,
	LAndExp,
	LOrExp,
	CondExp,
	AssignExp,
	AssignOp,
	Exp,
	ConstExp,
	Decln,
	DeclnSpec,
	InitDeclrList,
	InitDeclr,
	ClassSpec,
	TypeSpec,
	CompSpec,
	CompType,
	StructDeclnList,
	StructDecln,
	SpecQulfrList,
	StructDeclrList,
	StructDeclr,
	EnumSpec,
	EnumorList,
	Enumor,
	TypeQulfr,
	Declr,
	DirectDeclr,
	StarList,
	TypeQulfrList,
	ParaTypeList,
	ParaList,
	ParaDecln,
	IdList,
	TypeName,
	AbstDeclr,
	DirectAbstDeclr,
	Initializer,
	InitializerList,
	Stmt,
	LabelStmt,
	CompSt,
	DeclnList,
	StmtList,
	ExpStmt,
	SelectStmt,
	IterStmt,
	JmpStmt,
	Program,
	ExtDecln,
	FuncDef,
};

enum {
	AST_PriExp_is_ID,
	AST_PriExp_is_NUM,
	AST_PriExp_is_STRING,
	AST_PriExp_is_LITERAL,
	AST_PriExp_is_LP_Exp_RP,
	AST_PostExp_is_PriExp,
	AST_PostExp_is_PostExp_LB_Exp_RB,
	AST_PostExp_is_PostExp_LP_RP,
	AST_PostExp_is_PostExp_LP_ArgExpList_RP,
	AST_PostExp_is_PostExp_DOT_ID,
	AST_PostExp_is_PostExp_PTR_ID,
	AST_PostExp_is_PostExp_INC,
	AST_PostExp_is_PostExp_DEC,
	AST_ArgExpList_is_AssignExp,
	AST_ArgExpList_is_ArgExpList_COMMA_AssignExp,
	AST_UnaryExp_is_PostExp,
	AST_UnaryExp_is_INC_UnaryExp,
	AST_UnaryExp_is_DEC_UnaryExp,
	AST_UnaryExp_is_UnaryOp_CastExp,
	AST_UnaryExp_is_SIZEOF_UnaryExp,
	AST_UnaryExp_is_SIZEOF_LP_TypeName_RP,
	AST_UnaryOp_is_AND,
	AST_UnaryOp_is_MULT,
	AST_UnaryOp_is_ADD,
	AST_UnaryOp_is_SUB,
	AST_UnaryOp_is_NOT,
	AST_UnaryOp_is_LNOT,
	AST_CastExp_is_UnaryExp,
	AST_CastExp_is_LP_TypeName_RP_CastExp,
	AST_MulExp_is_CastExp,
	AST_MulExp_is_MulExp_MULT_CastExp,
	AST_MulExp_is_MulExp_DIV_CastExp,
	AST_MulExp_is_MulExp_MOD_CastExp,
	AST_AddExp_is_MulExp,
	AST_AddExp_is_AddExp_ADD_MulExp,
	AST_AddExp_is_AddExp_SUB_MulExp,
	AST_ShiftExp_is_AddExp,
	AST_ShiftExp_is_ShiftExp_LSHIFT_AddExp,
	AST_ShiftExp_is_ShiftExp_RSHIFT_AddExp,
	AST_RelExp_is_ShiftExp,
	AST_RelExp_is_RelExp_LT_ShiftExp,
	AST_RelExp_is_RelExp_GT_ShiftExp,
	AST_RelExp_is_RelExp_LE_ShiftExp,
	AST_RelExp_is_RelExp_GE_ShiftExp,
	AST_EquExp_is_RelExp,
	AST_EquExp_is_EquExp_EQ_RelExp,
	AST_EquExp_is_EquExp_NE_RelExp,
	AST_AndExp_is_EquExp,
	AST_AndExp_is_AndExp_AND_EquExp,
	AST_XorExp_is_AndExp,
	AST_XorExp_is_XorExp_XOR_AndExp,
	AST_OrExp_is_XorExp,
	AST_OrExp_is_OrExp_OR_XorExp,
	AST_LAndExp_is_OrExp,
	AST_LAndExp_is_LAndExp_AND_OrExp,
	AST_LOrExp_is_LAndExp,
	AST_LOrExp_is_LOrExp_OR_LAndExp,
	AST_CondExp_is_LOrExp,
	AST_CondExp_is_LOrExp_QOP_Exp_COLON_CondExp,
	AST_AssignExp_is_CondExp,
	AST_AssignExp_is_UnaryExp_AssignOp_AssignExp,
	AST_AssignOp_is_ASSIGN,
	AST_AssignOp_is_MULE,
	AST_AssignOp_is_DIVE,
	AST_AssignOp_is_MODE,
	AST_AssignOp_is_ADDE,
	AST_AssignOp_is_SUBE,
	AST_AssignOp_is_LSHIFTE,
	AST_AssignOp_is_RSHIFTE,
	AST_AssignOp_is_ANDE,
	AST_AssignOp_is_XORE,
	AST_AssignOp_is_ORE,
	AST_Exp_is_AssignExp,
	AST_Exp_is_Exp_COMMA_AssignExp,
	AST_ConstExp_is_CondExp,
	AST_Decln_is_DeclnSpec_SEMI,
	AST_Decln_is_DeclnSpec_InitDeclrList_SEMI,
	AST_DeclnSpec_is_ClassSpec,
	AST_DeclnSpec_is_ClassSpec_DeclnSpec,
	AST_DeclnSpec_is_TypeSpec,
	AST_DeclnSpec_is_TypeSpec_DeclnSpec,
	AST_DeclnSpec_is_TypeQulfr,
	AST_DeclnSpec_is_TypeQulfr_DeclnSpec,
	AST_InitDeclrList_is_InitDeclr,
	AST_InitDeclrList_is_InitDeclrList_COMMA_InitDeclr,
	AST_InitDeclr_is_Declr,
	AST_InitDeclr_is_Declr_DOT_Initializer,
	AST_ClassSpec_is_TYPEDEF,
	AST_ClassSpec_is_EXTERN,
	AST_ClassSpec_is_STATIC,
	AST_ClassSpec_is_AUTO,
	AST_ClassSpec_is_REGISTER,
	AST_TypeSpec_is_VOID,
	AST_TypeSpec_is_CHAR,
	AST_TypeSpec_is_SHORT,
	AST_TypeSpec_is_INT,
	AST_TypeSpec_is_LONG,
	AST_TypeSpec_is_FLOAT,
	AST_TypeSpec_is_DOUBLE,
	AST_TypeSpec_is_SIGNED,
	AST_TypeSpec_is_UNSIGNED,
	AST_TypeSpec_is_CompSpec,
	AST_TypeSpec_is_EnumSpec,
	AST_TypeSpec_is_TYPE_NAME,
	AST_CompSpec_is_CompType_ID_LC_StructDeclnList_RC,
	AST_CompSpec_is_CompType_LC_StructDeclnList_RC,
	AST_CompSpec_is_CompType_ID,
	AST_CompType_is_STRUCT,
	AST_CompType_is_UNION,
	AST_StructDeclnList_is_StructDecln,
	AST_StructDeclnList_is_StructDeclnList_StructDecln,
	AST_StructDecln_is_SpecQulfrList_StructDeclrList_SEMI,
	AST_SpecQulfrList_is_TypeSpec_SpecQulfrList,
	AST_SpecQulfrList_is_TypeSpec,
	AST_SpecQulfrList_is_TypeQulfr_SpecQulfrList,
	AST_SpecQulfrList_is_TypeQulfr,
	AST_StructDeclrList_is_StructDeclr,
	AST_StructDeclrList_is_StructDeclrList_COMMA_StructDeclr,
	AST_StructDeclr_is_Declr,
	AST_StructDeclr_is_COLON_ConstExp,
	AST_StructDeclr_is_Declr_COLON_ConstExp,
	AST_EnumSpec_is_ENUM_LC_EnumorList_RC,
	AST_EnumSpec_is_ENUM_ID_LC_EnumorList_RC,
	AST_EnumSpec_is_ENUM_ID,
	AST_EnumorList_is_Enumor,
	AST_EnumorList_is_EnumorList_COMMA_Enumor,
	AST_Enumor_is_ID,
	AST_Enumor_is_ID_ASSIGN_ConstExp,
	AST_TypeQulfr_is_CONST,
	AST_TypeQulfr_is_VOLATILE,
	AST_Declr_is_StarList_DirectDeclr,
	AST_Declr_is_DirectDeclr,
	AST_DirectDeclr_is_ID,
	AST_DirectDeclr_is_LP_Declr_RP,
	AST_DirectDeclr_is_LB_ConstExp_RB,
	AST_DirectDeclr_is_DirectDeclr_LB_RB,
	AST_DirectDeclr_is_DirectDeclr_LP_ParaTypeList_RP,
	AST_DirectDeclr_is_DirectDeclr_LP_IdList_RP,
	AST_DirectDeclr_is_DirectDeclr_LP_RP,
	AST_StarList_is_MULT,
	AST_StarList_is_MULT_TypeQulfrList,
	AST_StarList_is_MULT_StarList,
	AST_StarList_is_MULT_TypeQulfrList_StarList,
	AST_TypeQulfrList_is_TypeQulfr,
	AST_TypeQulfrList_is_TypeQulfrList_TypeQulfr,
	AST_ParaTypeList_is_ParaList,
	AST_ParaTypeList_is_ParaList_COMMA_ELLIPSIS,
	AST_ParaList_is_ParaDecln,
	AST_ParaList_is_ParaList_COMMA_ParaDecln,
	AST_ParaDecln_is_DeclnSpec_Declr,
	AST_ParaDecln_is_DeclnSpec_AbstDeclr,
	AST_ParaDecln_is_DeclnSpec,
	AST_IdList_is_ID,
	AST_IdList_is_IdList_COMMA_ID,
	AST_TypeName_is_SpecQulfrList,
	AST_TypeName_is_SpecQulfrList_AbstDeclr,
	AST_AbstDeclr_is_StarList,
	AST_AbstDeclr_is_DirectAbstDeclr,
	AST_AbstDeclr_is_StarList_DirectAbstDeclr,
	AST_DirectAbstDeclr_is_LP_AbstDeclr_RP,
	AST_DirectAbstDeclr_is_LB_RB,
	AST_DirectAbstDeclr_is_LB_ConstExp_RB,
	AST_DirectAbstDeclr_is_DirectAbstDeclr_LB_RB,
	AST_DirectAbstDeclr_is_DirectAbstDeclr_LB_ConstExp_RB,
	AST_DirectAbstDeclr_is_LP_RP,
	AST_DirectAbstDeclr_is_LP_ParaTypeList_RP,
	AST_DirectAbstDeclr_is_DirectAbstDeclr_LP_RP,
	AST_DirectAbstDeclr_is_DirectAbstDeclr_LP_ParaTypeList_RP,
	AST_Initializer_is_AssignExp,
	AST_Initializer_is_LC_InitializerList_RC,
	AST_Initializer_is_LC_InitializerList_COMMA_RC,
	AST_InitializerList_is_Initializer,
	AST_InitializerList_is_InitializerList_COMMA_Initializer,
	AST_Stmt_is_LabelStmt,
	AST_Stmt_is_CompSt,
	AST_Stmt_is_ExpStmt,
	AST_Stmt_is_SelectStmt,
	AST_Stmt_is_IterStmt,
	AST_Stmt_is_JmpStmt,
	AST_LabelStmt_is_ID_COLON_Stmt,
	AST_LabelStmt_is_CASE_ConstExp_COLON_Stmt,
	AST_LabelStmt_is_DEFAULT_COLON_Stmt,
	AST_CompSt_is_LC_RC,
	AST_CompSt_is_LC_StmtList_RC,
	AST_CompSt_is_LC_DeclnList_RC,
	AST_CompSt_is_LC_DeclnList_StmtList_RC,
	AST_DeclnList_is_Decln,
	AST_DeclnList_is_DeclnList_Decln,
	AST_StmtList_is_Stmt,
	AST_StmtList_is_StmtList_Stmt,
	AST_ExpStmt_is_SEMI,
	AST_ExpStmt_is_Exp_SEMI,
	AST_SelectStmt_is_IF_LP_Exp_RP_Stmt,
	AST_SelectStmt_is_IF_LP_Exp_RP_Stmt_ELSE_Stmt,
	AST_SelectStmt_is_SWITCH_LP_Exp_RP_Stmt,
	AST_IterStmt_is_WHILE_LP_Exp_RP_Stmt,
	AST_IterStmt_is_DO_Stmt_WHILE_LP_Exp_RP_SEMI,
	AST_IterStmt_is_FOR_LP_ExpStmt_ExpStmt_RP_Stmt,
	AST_IterStmt_is_FOR_LP_ExpStmt_ExpStmt_Exp_RP_Stmt,
	AST_JmpStmt_is_GOTO_ID_SEMI,
	AST_JmpStmt_is_CONTINUE_SEMI,
	AST_JmpStmt_is_BREAK_SEMI,
	AST_JmpStmt_is_RETURN_SEMI,
	AST_JmpStmt_is_RETURN_Exp_SEMI,
	AST_Program_is_ExtDecln,
	AST_Program_is_Program_ExtDecln,
	AST_ExtDecln_is_FuncDef,
	AST_ExtDecln_is_Decln,
	AST_FuncDef_is_DeclnSpec_Declr_DeclnList_CompSt,
	AST_FuncDef_is_DeclnSpec_Declr_CompSt,
	AST_FuncDef_is_Declr_DeclnList_CompSt,
	AST_FuncDef_is_Declr_CompSt,
};

struct {
	int root, len;
	int child[10];
} syntaxrules[] = {
	[AST_PriExp_is_ID] = {PriExp, 1, {ID}},
	[AST_PriExp_is_NUM] = {PriExp, 1, {NUM}},
	[AST_PriExp_is_STRING] = {PriExp, 1, {STRING}},
	[AST_PriExp_is_LITERAL] = {PriExp, 1, {LITERAL}},
	[AST_PriExp_is_LP_Exp_RP] = {PriExp, 3, {LP, Exp, RP}},
	[AST_PostExp_is_PriExp] = {PostExp, 1, {PriExp}},
	[AST_PostExp_is_PostExp_LB_Exp_RB] = {PostExp, 4, {PostExp, LB, Exp, RB}},
	[AST_PostExp_is_PostExp_LP_RP] = {PostExp, 3, {PostExp, LP, RP}},
	[AST_PostExp_is_PostExp_LP_ArgExpList_RP] = {PostExp, 4, {PostExp, LP, ArgExpList, RP}},
	[AST_PostExp_is_PostExp_DOT_ID] = {PostExp, 3, {PostExp, DOT, ID}},
	[AST_PostExp_is_PostExp_PTR_ID] = {PostExp, 3, {PostExp, PTR, ID}},
	[AST_PostExp_is_PostExp_INC] = {PostExp, 2, {PostExp, INC}},
	[AST_PostExp_is_PostExp_DEC] = {PostExp, 2, {PostExp, DEC}},
	[AST_ArgExpList_is_AssignExp] = {ArgExpList, 1, {AssignExp}},
	[AST_ArgExpList_is_ArgExpList_COMMA_AssignExp] = {ArgExpList, 3, {ArgExpList, COMMA, AssignExp}},
	[AST_UnaryExp_is_PostExp] = {UnaryExp, 1, {PostExp}},
	[AST_UnaryExp_is_INC_UnaryExp] = {UnaryExp, 2, {INC, UnaryExp}},
	[AST_UnaryExp_is_DEC_UnaryExp] = {UnaryExp, 2, {DEC, UnaryExp}},
	[AST_UnaryExp_is_UnaryOp_CastExp] = {UnaryExp, 2, {UnaryOp, CastExp}},
	[AST_UnaryExp_is_SIZEOF_UnaryExp] = {UnaryExp, 2, {SIZEOF, UnaryExp}},
	[AST_UnaryExp_is_SIZEOF_LP_TypeName_RP] = {UnaryExp, 4, {SIZEOF, LP, TypeName, RP}},
	[AST_UnaryOp_is_AND] = {UnaryOp, 1, {AND}},
	[AST_UnaryOp_is_MULT] = {UnaryOp, 1, {MULT}},
	[AST_UnaryOp_is_ADD] = {UnaryOp, 1, {ADD}},
	[AST_UnaryOp_is_SUB] = {UnaryOp, 1, {SUB}},
	[AST_UnaryOp_is_NOT] = {UnaryOp, 1, {NOT}},
	[AST_UnaryOp_is_LNOT] = {UnaryOp, 1, {LNOT}},
	[AST_CastExp_is_UnaryExp] = {CastExp, 1, {UnaryExp}},
	[AST_CastExp_is_LP_TypeName_RP_CastExp] = {CastExp, 4, {LP, TypeName, RP, CastExp}},
	[AST_MulExp_is_CastExp] = {MulExp, 1, {CastExp}},
	[AST_MulExp_is_MulExp_MULT_CastExp] = {MulExp, 3, {MulExp, MULT, CastExp}},
	[AST_MulExp_is_MulExp_DIV_CastExp] = {MulExp, 3, {MulExp, DIV, CastExp}},
	[AST_MulExp_is_MulExp_MOD_CastExp] = {MulExp, 3, {MulExp, MOD, CastExp}},
	[AST_AddExp_is_MulExp] = {AddExp, 1, {MulExp}},
	[AST_AddExp_is_AddExp_ADD_MulExp] = {AddExp, 3, {AddExp, ADD, MulExp}},
	[AST_AddExp_is_AddExp_SUB_MulExp] = {AddExp, 3, {AddExp, SUB, MulExp}},
	[AST_ShiftExp_is_AddExp] = {ShiftExp, 1, {AddExp}},
	[AST_ShiftExp_is_ShiftExp_LSHIFT_AddExp] = {ShiftExp, 3, {ShiftExp, LSHIFT, AddExp}},
	[AST_ShiftExp_is_ShiftExp_RSHIFT_AddExp] = {ShiftExp, 3, {ShiftExp, RSHIFT, AddExp}},
	[AST_RelExp_is_ShiftExp] = {RelExp, 1, {ShiftExp}},
	[AST_RelExp_is_RelExp_LT_ShiftExp] = {RelExp, 3, {RelExp, LT, ShiftExp}},
	[AST_RelExp_is_RelExp_GT_ShiftExp] = {RelExp, 3, {RelExp, GT, ShiftExp}},
	[AST_RelExp_is_RelExp_LE_ShiftExp] = {RelExp, 3, {RelExp, LE, ShiftExp}},
	[AST_RelExp_is_RelExp_GE_ShiftExp] = {RelExp, 3, {RelExp, GE, ShiftExp}},
	[AST_EquExp_is_RelExp] = {EquExp, 1, {RelExp}},
	[AST_EquExp_is_EquExp_EQ_RelExp] = {EquExp, 3, {EquExp, EQ, RelExp}},
	[AST_EquExp_is_EquExp_NE_RelExp] = {EquExp, 3, {EquExp, NE, RelExp}},
	[AST_AndExp_is_EquExp] = {AndExp, 1, {EquExp}},
	[AST_AndExp_is_AndExp_AND_EquExp] = {AndExp, 3, {AndExp, AND, EquExp}},
	[AST_XorExp_is_AndExp] = {XorExp, 1, {AndExp}},
	[AST_XorExp_is_XorExp_XOR_AndExp] = {XorExp, 3, {XorExp, XOR, AndExp}},
	[AST_OrExp_is_XorExp] = {OrExp, 1, {XorExp}},
	[AST_OrExp_is_OrExp_OR_XorExp] = {OrExp, 3, {OrExp, OR, XorExp}},
	[AST_LAndExp_is_OrExp] = {LAndExp, 1, {OrExp}},
	[AST_LAndExp_is_LAndExp_AND_OrExp] = {LAndExp, 3, {LAndExp, AND, OrExp}},
	[AST_LOrExp_is_LAndExp] = {LOrExp, 1, {LAndExp}},
	[AST_LOrExp_is_LOrExp_OR_LAndExp] = {LOrExp, 3, {LOrExp, OR, LAndExp}},
	[AST_CondExp_is_LOrExp] = {CondExp, 1, {LOrExp}},
	[AST_CondExp_is_LOrExp_QOP_Exp_COLON_CondExp] = {CondExp, 5, {LOrExp, QOP, Exp, COLON, CondExp}},
	[AST_AssignExp_is_CondExp] = {AssignExp, 1, {CondExp}},
	[AST_AssignExp_is_UnaryExp_AssignOp_AssignExp] = {AssignExp, 3, {UnaryExp, AssignOp, AssignExp}},
	[AST_AssignOp_is_ASSIGN] = {AssignOp, 1, {ASSIGN}},
	[AST_AssignOp_is_MULE] = {AssignOp, 1, {MULE}},
	[AST_AssignOp_is_DIVE] = {AssignOp, 1, {DIVE}},
	[AST_AssignOp_is_MODE] = {AssignOp, 1, {MODE}},
	[AST_AssignOp_is_ADDE] = {AssignOp, 1, {ADDE}},
	[AST_AssignOp_is_SUBE] = {AssignOp, 1, {SUBE}},
	[AST_AssignOp_is_LSHIFTE] = {AssignOp, 1, {LSHIFTE}},
	[AST_AssignOp_is_RSHIFTE] = {AssignOp, 1, {RSHIFTE}},
	[AST_AssignOp_is_ANDE] = {AssignOp, 1, {ANDE}},
	[AST_AssignOp_is_XORE] = {AssignOp, 1, {XORE}},
	[AST_AssignOp_is_ORE] = {AssignOp, 1, {ORE}},
	[AST_Exp_is_AssignExp] = {Exp, 1, {AssignExp}},
	[AST_Exp_is_Exp_COMMA_AssignExp] = {Exp, 3, {Exp, COMMA, AssignExp}},
	[AST_ConstExp_is_CondExp] = {ConstExp, 1, {CondExp}},
	[AST_Decln_is_DeclnSpec_SEMI] = {Decln, 2, {DeclnSpec, SEMI}},
	[AST_Decln_is_DeclnSpec_InitDeclrList_SEMI] = {Decln, 3, {DeclnSpec, InitDeclrList, SEMI}},
	[AST_DeclnSpec_is_ClassSpec] = {DeclnSpec, 1, {ClassSpec}},
	[AST_DeclnSpec_is_ClassSpec_DeclnSpec] = {DeclnSpec, 2, {ClassSpec, DeclnSpec}},
	[AST_DeclnSpec_is_TypeSpec] = {DeclnSpec, 1, {TypeSpec}},
	[AST_DeclnSpec_is_TypeSpec_DeclnSpec] = {DeclnSpec, 2, {TypeSpec, DeclnSpec}},
	[AST_DeclnSpec_is_TypeQulfr] = {DeclnSpec, 1, {TypeQulfr}},
	[AST_DeclnSpec_is_TypeQulfr_DeclnSpec] = {DeclnSpec, 2, {TypeQulfr, DeclnSpec}},
	[AST_InitDeclrList_is_InitDeclr] = {InitDeclrList, 1, {InitDeclr}},
	[AST_InitDeclrList_is_InitDeclrList_COMMA_InitDeclr] = {InitDeclrList, 3, {InitDeclrList, COMMA, InitDeclr}},
	[AST_InitDeclr_is_Declr] = {InitDeclr, 1, {Declr}},
	[AST_InitDeclr_is_Declr_DOT_Initializer] = {InitDeclr, 3, {Declr, DOT, Initializer}},
	[AST_ClassSpec_is_TYPEDEF] = {ClassSpec, 1, {TYPEDEF}},
	[AST_ClassSpec_is_EXTERN] = {ClassSpec, 1, {EXTERN}},
	[AST_ClassSpec_is_STATIC] = {ClassSpec, 1, {STATIC}},
	[AST_ClassSpec_is_AUTO] = {ClassSpec, 1, {AUTO}},
	[AST_ClassSpec_is_REGISTER] = {ClassSpec, 1, {REGISTER}},
	[AST_TypeSpec_is_VOID] = {TypeSpec, 1, {VOID}},
	[AST_TypeSpec_is_CHAR] = {TypeSpec, 1, {CHAR}},
	[AST_TypeSpec_is_SHORT] = {TypeSpec, 1, {SHORT}},
	[AST_TypeSpec_is_INT] = {TypeSpec, 1, {INT}},
	[AST_TypeSpec_is_LONG] = {TypeSpec, 1, {LONG}},
	[AST_TypeSpec_is_FLOAT] = {TypeSpec, 1, {FLOAT}},
	[AST_TypeSpec_is_DOUBLE] = {TypeSpec, 1, {DOUBLE}},
	[AST_TypeSpec_is_SIGNED] = {TypeSpec, 1, {SIGNED}},
	[AST_TypeSpec_is_UNSIGNED] = {TypeSpec, 1, {UNSIGNED}},
	[AST_TypeSpec_is_CompSpec] = {TypeSpec, 1, {CompSpec}},
	[AST_TypeSpec_is_EnumSpec] = {TypeSpec, 1, {EnumSpec}},
	[AST_TypeSpec_is_TYPE_NAME] = {TypeSpec, 1, {TYPE_NAME}},
	[AST_CompSpec_is_CompType_ID_LC_StructDeclnList_RC] = {CompSpec, 5, {CompType, ID, LC, StructDeclnList, RC}},
	[AST_CompSpec_is_CompType_LC_StructDeclnList_RC] = {CompSpec, 4, {CompType, LC, StructDeclnList, RC}},
	[AST_CompSpec_is_CompType_ID] = {CompSpec, 2, {CompType, ID}},
	[AST_CompType_is_STRUCT] = {CompType, 1, {STRUCT}},
	[AST_CompType_is_UNION] = {CompType, 1, {UNION}},
	[AST_StructDeclnList_is_StructDecln] = {StructDeclnList, 1, {StructDecln}},
	[AST_StructDeclnList_is_StructDeclnList_StructDecln] = {StructDeclnList, 2, {StructDeclnList, StructDecln}},
	[AST_StructDecln_is_SpecQulfrList_StructDeclrList_SEMI] = {StructDecln, 3, {SpecQulfrList, StructDeclrList, SEMI}},
	[AST_SpecQulfrList_is_TypeSpec_SpecQulfrList] = {SpecQulfrList, 2, {TypeSpec, SpecQulfrList}},
	[AST_SpecQulfrList_is_TypeSpec] = {SpecQulfrList, 1, {TypeSpec}},
	[AST_SpecQulfrList_is_TypeQulfr_SpecQulfrList] = {SpecQulfrList, 2, {TypeQulfr, SpecQulfrList}},
	[AST_SpecQulfrList_is_TypeQulfr] = {SpecQulfrList, 1, {TypeQulfr}},
	[AST_StructDeclrList_is_StructDeclr] = {StructDeclrList, 1, {StructDeclr}},
	[AST_StructDeclrList_is_StructDeclrList_COMMA_StructDeclr] = {StructDeclrList, 3, {StructDeclrList, COMMA, StructDeclr}},
	[AST_StructDeclr_is_Declr] = {StructDeclr, 1, {Declr}},
	[AST_StructDeclr_is_COLON_ConstExp] = {StructDeclr, 2, {COLON, ConstExp}},
	[AST_StructDeclr_is_Declr_COLON_ConstExp] = {StructDeclr, 3, {Declr, COLON, ConstExp}},
	[AST_EnumSpec_is_ENUM_LC_EnumorList_RC] = {EnumSpec, 4, {ENUM, LC, EnumorList, RC}},
	[AST_EnumSpec_is_ENUM_ID_LC_EnumorList_RC] = {EnumSpec, 5, {ENUM, ID, LC, EnumorList, RC}},
	[AST_EnumSpec_is_ENUM_ID] = {EnumSpec, 2, {ENUM, ID}},
	[AST_EnumorList_is_Enumor] = {EnumorList, 1, {Enumor}},
	[AST_EnumorList_is_EnumorList_COMMA_Enumor] = {EnumorList, 3, {EnumorList, COMMA, Enumor}},
	[AST_Enumor_is_ID] = {Enumor, 1, {ID}},
	[AST_Enumor_is_ID_ASSIGN_ConstExp] = {Enumor, 3, {ID, ASSIGN, ConstExp}},
	[AST_TypeQulfr_is_CONST] = {TypeQulfr, 1, {CONST}},
	[AST_TypeQulfr_is_VOLATILE] = {TypeQulfr, 1, {VOLATILE}},
	[AST_Declr_is_StarList_DirectDeclr] = {Declr, 2, {StarList, DirectDeclr}},
	[AST_Declr_is_DirectDeclr] = {Declr, 1, {DirectDeclr}},
	[AST_DirectDeclr_is_ID] = {DirectDeclr, 1, {ID}},
	[AST_DirectDeclr_is_LP_Declr_RP] = {DirectDeclr, 3, {LP, Declr, RP}},
	[AST_DirectDeclr_is_LB_ConstExp_RB] = {DirectDeclr, 3, {LB, ConstExp, RB}},
	[AST_DirectDeclr_is_DirectDeclr_LB_RB] = {DirectDeclr, 3, {DirectDeclr, LB, RB}},
	[AST_DirectDeclr_is_DirectDeclr_LP_ParaTypeList_RP] = {DirectDeclr, 4, {DirectDeclr, LP, ParaTypeList, RP}},
	[AST_DirectDeclr_is_DirectDeclr_LP_IdList_RP] = {DirectDeclr, 4, {DirectDeclr, LP, IdList, RP}},
	[AST_DirectDeclr_is_DirectDeclr_LP_RP] = {DirectDeclr, 3, {DirectDeclr, LP, RP}},
	[AST_StarList_is_MULT] = {StarList, 1, {MULT}},
	[AST_StarList_is_MULT_TypeQulfrList] = {StarList, 2, {MULT, TypeQulfrList}},
	[AST_StarList_is_MULT_StarList] = {StarList, 2, {MULT, StarList}},
	[AST_StarList_is_MULT_TypeQulfrList_StarList] = {StarList, 3, {MULT, TypeQulfrList, StarList}},
	[AST_TypeQulfrList_is_TypeQulfr] = {TypeQulfrList, 1, {TypeQulfr}},
	[AST_TypeQulfrList_is_TypeQulfrList_TypeQulfr] = {TypeQulfrList, 2, {TypeQulfrList, TypeQulfr}},
	[AST_ParaTypeList_is_ParaList] = {ParaTypeList, 1, {ParaList}},
	[AST_ParaTypeList_is_ParaList_COMMA_ELLIPSIS] = {ParaTypeList, 3, {ParaList, COMMA, ELLIPSIS}},
	[AST_ParaList_is_ParaDecln] = {ParaList, 1, {ParaDecln}},
	[AST_ParaList_is_ParaList_COMMA_ParaDecln] = {ParaList, 3, {ParaList, COMMA, ParaDecln}},
	[AST_ParaDecln_is_DeclnSpec_Declr] = {ParaDecln, 2, {DeclnSpec, Declr}},
	[AST_ParaDecln_is_DeclnSpec_AbstDeclr] = {ParaDecln, 2, {DeclnSpec, AbstDeclr}},
	[AST_ParaDecln_is_DeclnSpec] = {ParaDecln, 1, {DeclnSpec}},
	[AST_IdList_is_ID] = {IdList, 1, {ID}},
	[AST_IdList_is_IdList_COMMA_ID] = {IdList, 3, {IdList, COMMA, ID}},
	[AST_TypeName_is_SpecQulfrList] = {TypeName, 1, {SpecQulfrList}},
	[AST_TypeName_is_SpecQulfrList_AbstDeclr] = {TypeName, 2, {SpecQulfrList, AbstDeclr}},
	[AST_AbstDeclr_is_StarList] = {AbstDeclr, 1, {StarList}},
	[AST_AbstDeclr_is_DirectAbstDeclr] = {AbstDeclr, 1, {DirectAbstDeclr}},
	[AST_AbstDeclr_is_StarList_DirectAbstDeclr] = {AbstDeclr, 2, {StarList, DirectAbstDeclr}},
	[AST_DirectAbstDeclr_is_LP_AbstDeclr_RP] = {DirectAbstDeclr, 3, {LP, AbstDeclr, RP}},
	[AST_DirectAbstDeclr_is_LB_RB] = {DirectAbstDeclr, 2, {LB, RB}},
	[AST_DirectAbstDeclr_is_LB_ConstExp_RB] = {DirectAbstDeclr, 3, {LB, ConstExp, RB}},
	[AST_DirectAbstDeclr_is_DirectAbstDeclr_LB_RB] = {DirectAbstDeclr, 3, {DirectAbstDeclr, LB, RB}},
	[AST_DirectAbstDeclr_is_DirectAbstDeclr_LB_ConstExp_RB] = {DirectAbstDeclr, 4, {DirectAbstDeclr, LB, ConstExp, RB}},
	[AST_DirectAbstDeclr_is_LP_RP] = {DirectAbstDeclr, 2, {LP, RP}},
	[AST_DirectAbstDeclr_is_LP_ParaTypeList_RP] = {DirectAbstDeclr, 3, {LP, ParaTypeList, RP}},
	[AST_DirectAbstDeclr_is_DirectAbstDeclr_LP_RP] = {DirectAbstDeclr, 3, {DirectAbstDeclr, LP, RP}},
	[AST_DirectAbstDeclr_is_DirectAbstDeclr_LP_ParaTypeList_RP] = {DirectAbstDeclr, 4, {DirectAbstDeclr, LP, ParaTypeList, RP}},
	[AST_Initializer_is_AssignExp] = {Initializer, 1, {AssignExp}},
	[AST_Initializer_is_LC_InitializerList_RC] = {Initializer, 3, {LC, InitializerList, RC}},
	[AST_Initializer_is_LC_InitializerList_COMMA_RC] = {Initializer, 4, {LC, InitializerList, COMMA, RC}},
	[AST_InitializerList_is_Initializer] = {InitializerList, 1, {Initializer}},
	[AST_InitializerList_is_InitializerList_COMMA_Initializer] = {InitializerList, 3, {InitializerList, COMMA, Initializer}},
	[AST_Stmt_is_LabelStmt] = {Stmt, 1, {LabelStmt}},
	[AST_Stmt_is_CompSt] = {Stmt, 1, {CompSt}},
	[AST_Stmt_is_ExpStmt] = {Stmt, 1, {ExpStmt}},
	[AST_Stmt_is_SelectStmt] = {Stmt, 1, {SelectStmt}},
	[AST_Stmt_is_IterStmt] = {Stmt, 1, {IterStmt}},
	[AST_Stmt_is_JmpStmt] = {Stmt, 1, {JmpStmt}},
	[AST_LabelStmt_is_ID_COLON_Stmt] = {LabelStmt, 3, {ID, COLON, Stmt}},
	[AST_LabelStmt_is_CASE_ConstExp_COLON_Stmt] = {LabelStmt, 4, {CASE, ConstExp, COLON, Stmt}},
	[AST_LabelStmt_is_DEFAULT_COLON_Stmt] = {LabelStmt, 3, {DEFAULT, COLON, Stmt}},
	[AST_CompSt_is_LC_RC] = {CompSt, 2, {LC, RC}},
	[AST_CompSt_is_LC_StmtList_RC] = {CompSt, 3, {LC, StmtList, RC}},
	[AST_CompSt_is_LC_DeclnList_RC] = {CompSt, 3, {LC, DeclnList, RC}},
	[AST_CompSt_is_LC_DeclnList_StmtList_RC] = {CompSt, 4, {LC, DeclnList, StmtList, RC}},
	[AST_DeclnList_is_Decln] = {DeclnList, 1, {Decln}},
	[AST_DeclnList_is_DeclnList_Decln] = {DeclnList, 2, {DeclnList, Decln}},
	[AST_StmtList_is_Stmt] = {StmtList, 1, {Stmt}},
	[AST_StmtList_is_StmtList_Stmt] = {StmtList, 2, {StmtList, Stmt}},
	[AST_ExpStmt_is_SEMI] = {ExpStmt, 1, {SEMI}},
	[AST_ExpStmt_is_Exp_SEMI] = {ExpStmt, 2, {Exp, SEMI}},
	[AST_SelectStmt_is_IF_LP_Exp_RP_Stmt] = {SelectStmt, 5, {IF, LP, Exp, RP, Stmt}},
	[AST_SelectStmt_is_IF_LP_Exp_RP_Stmt_ELSE_Stmt] = {SelectStmt, 7, {IF, LP, Exp, RP, Stmt, ELSE, Stmt}},
	[AST_SelectStmt_is_SWITCH_LP_Exp_RP_Stmt] = {SelectStmt, 5, {SWITCH, LP, Exp, RP, Stmt}},
	[AST_IterStmt_is_WHILE_LP_Exp_RP_Stmt] = {IterStmt, 5, {WHILE, LP, Exp, RP, Stmt}},
	[AST_IterStmt_is_DO_Stmt_WHILE_LP_Exp_RP_SEMI] = {IterStmt, 7, {DO, Stmt, WHILE, LP, Exp, RP, SEMI}},
	[AST_IterStmt_is_FOR_LP_ExpStmt_ExpStmt_RP_Stmt] = {IterStmt, 6, {FOR, LP, ExpStmt, ExpStmt, RP, Stmt}},
	[AST_IterStmt_is_FOR_LP_ExpStmt_ExpStmt_Exp_RP_Stmt] = {IterStmt, 7, {FOR, LP, ExpStmt, ExpStmt, Exp, RP, Stmt}},
	[AST_JmpStmt_is_GOTO_ID_SEMI] = {JmpStmt, 3, {GOTO, ID, SEMI}},
	[AST_JmpStmt_is_CONTINUE_SEMI] = {JmpStmt, 2, {CONTINUE, SEMI}},
	[AST_JmpStmt_is_BREAK_SEMI] = {JmpStmt, 2, {BREAK, SEMI}},
	[AST_JmpStmt_is_RETURN_SEMI] = {JmpStmt, 2, {RETURN, SEMI}},
	[AST_JmpStmt_is_RETURN_Exp_SEMI] = {JmpStmt, 3, {RETURN, Exp, SEMI}},
	[AST_Program_is_ExtDecln] = {Program, 1, {ExtDecln}},
	[AST_Program_is_Program_ExtDecln] = {Program, 2, {Program, ExtDecln}},
	[AST_ExtDecln_is_FuncDef] = {ExtDecln, 1, {FuncDef}},
	[AST_ExtDecln_is_Decln] = {ExtDecln, 1, {Decln}},
	[AST_FuncDef_is_DeclnSpec_Declr_DeclnList_CompSt] = {FuncDef, 4, {DeclnSpec, Declr, DeclnList, CompSt}},
	[AST_FuncDef_is_DeclnSpec_Declr_CompSt] = {FuncDef, 3, {DeclnSpec, Declr, CompSt}},
	[AST_FuncDef_is_Declr_DeclnList_CompSt] = {FuncDef, 3, {Declr, DeclnList, CompSt}},
	[AST_FuncDef_is_Declr_CompSt] = {FuncDef, 2, {Declr, CompSt}},
};

//recursive descent

/* entry of parser
 */
Node *wt_match_program() {
	int token = yylex();

}

Node *wt_match_exp() {
	return NULL;
}
