#line 2 "front/lexical.c"

#line 4 "front/lexical.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 124
#define YY_END_OF_BUFFER 125
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[378] =
    {   0,
        0,    0,  125,  123,   66,   65,   49,  123,   10,   32,
       43,  123,   51,   52,   30,   28,   59,   29,   57,   31,
      112,  112,   61,   62,   20,   17,   22,   60,  119,  119,
       53,  123,   54,   45,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,   55,   44,   56,   46,   66,   10,   66,   19,    0,
      118,    0,   11,   39,   47,   40,    0,  117,    0,   37,
       33,   35,   34,   36,   58,    0,  115,    0,    0,   38,
      115,  116,  114,  116,  116,  112,   24,   21,   18,   23,
       25,  119,  119,   64,   42,  119,  119,  119,  119,  119,

      119,  119,  119,   96,  119,  119,  119,  119,  119,  119,
      119,   94,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,   41,   48,   66,    0,
        0,    0,    0,    0,    0,    0,    0,  118,    0,  118,
      117,    0,  117,   63,  116,  115,  116,    0,  122,    0,
        0,  121,  115,  114,  113,   26,   27,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,   98,  119,   71,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,    0,    0,    0,    0,

        3,    0,    0,    0,  118,  118,  117,  117,    0,    0,
      115,  120,   91,  119,  119,  119,  119,  108,   68,  119,
      101,   69,  119,  119,  119,  119,   95,   88,  119,  119,
      119,  104,  119,  119,  119,  119,   72,  119,  119,  119,
      119,  119,  119,  119,  119,  119,   92,  119,  119,  119,
      119,   67,  119,  119,    0,    0,    0,    0,    0,    0,
        0,    0,  115,  119,  119,  119,  119,  102,  110,  119,
      119,  119,  119,   93,   75,  119,  119,  119,  119,   87,
      119,  119,   70,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,   89,  119,  119,   97,    0,

        4,    5,    0,    0,    7,    0,    0,  119,  119,  119,
      119,  119,  119,   76,  106,  119,  119,  119,   77,  119,
       99,   73,   85,   50,  107,   90,  100,  119,  119,  119,
      119,  119,  119,  119,  119,    0,    6,    9,    2,    0,
      119,  119,  119,  119,  103,   16,   78,   79,   80,  119,
      105,  119,  119,  119,   81,  119,  119,  119,    1,    0,
       14,   12,  119,   13,  109,   82,   83,   84,  119,   74,
      111,    8,  119,   86,  119,   15,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   27,   28,   29,   30,
       31,   32,   33,    1,   34,   35,   35,   35,   36,   37,
       38,   39,   40,   39,   39,   41,   39,   42,   39,   39,
       39,   43,   44,   39,   45,   46,   39,   47,   39,   39,
       48,   49,   50,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   39,   62,   63,   64,   65,
       66,   67,   39,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[81] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[384] =
    {   0,
        0,   79,  630,  631,   80,  631,  598,   79,  621,  596,
       78,   78,  631,  631,  595,   75,  631,   76,   74,   92,
       94,  112,  631,  631,   72,  594,   93,  631,    0,  579,
      631,  620,  631,  591,  569,  549,   74,   90,   87,   83,
       92,  553,   89,  552,  559,  559,   91,   91,   61,  549,
      554,  631,   99,  631,  631,  158,  165,  169,  631,  143,
      172,  157,  631,  631,  631,  631,  160,  177,  166,  631,
      631,  631,  631,  631,  631,  174,  220,  199,  610,  631,
      238,  247,  259,    0,  268,    0,  581,  631,  631,  631,
      580,    0,  569,  631,  631,  167,  539,  542,  550,  537,

      552,  539,  545,  531,  532,  529,  529,  535,  531,  528,
      525,    0,  524,  528,  534,  144,  525,  129,  163,  529,
      518,  521,  522,   43,  120,  525,  631,  631,  182,  294,
      297,  528,  155,  526,  522,  517,  528,  227,  201,  307,
      304,  175,  317,  311,    0,    0,  355,  214,  305,  562,
      576,  631,  320,  364,    0,  631,  631,  537,  537,  536,
      541,  503,  507,  509,  518,  513,  501,  499,  129,  513,
      509,  501,  507,  494,  509,    0,  495,  229,  501,  507,
      497,  486,  488,  490,  497,  483,  481,  481,  493,  492,
      478,  481,  485,  489,  491,  480,  484,  150,  485,  472,

      631,  474,  482,  469,  346,  390,  395,  397,  389,  398,
      218,  631,    0,  495,  493,  482,  468,    0,    0,  470,
        0,    0,  461,  459,  464,  465,    0,    0,  459,  469,
      455,    0,  499,  502,  499,  469,    0,  450,  450,  450,
      447,  459,  245,  454,  459,  458,    0,  456,  406,  446,
      451,    0,  439,  451,  446,  448,  448,  443,  437,  445,
      444,  435,  428,  463,  462,  463,  441,    0,    0,  432,
      437,  436,  427,    0,    0,  439,  438,  437,  418,    0,
      402,  406,    0,  414,  399,  410,  412,  396,  405,  407,
      438,  441,  438,  408,  389,    0,  393,  396,    0,  391,

      631,  631,  387,  375,  631,  384,  380,  388,  386,  394,
      384,  365,  378,    0,    0,  363,  360,  359,    0,  370,
        0,    0,    0,    0,    0,    0,    0,  346,  351,  350,
      349,  324,  305,  315,  301,  306,  631,  631,  631,  297,
      309,  307,  291,  265,    0,    0,    0,    0,    0,  248,
        0,  245,  242,  230,    0,  224,  219,  196,  631,  193,
        0,    0,  204,    0,    0,    0,    0,    0,  167,    0,
        0,  631,  183,    0,  158,    0,  631,  473,  476,  478,
       87,  481,  484
    } ;

static yyconst flex_int16_t yy_def[384] =
    {   0,
      377,    1,  377,  377,  377,  377,  377,  378,  377,  377,
      377,  379,  377,  377,  377,  377,  377,  377,  377,  377,
      380,  380,  377,  377,  377,  377,  377,  377,  381,  381,
      377,  377,  377,  377,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  377,  377,  377,  377,  377,  377,  377,  377,  378,
      377,  378,  377,  377,  377,  377,  379,  377,  379,  377,
      377,  377,  377,  377,  377,  377,  380,  382,  383,  377,
       77,   22,   22,  380,  380,   22,  377,  377,  377,  377,
      377,  381,  381,  377,  377,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  378,  378,
      377,  379,  379,  377,  380,   77,  380,  382,  382,  382,
      383,  377,   77,   22,   85,  377,  377,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  377,  377,  377,  377,

      377,  377,  377,  377,  378,  378,  379,  379,  377,  377,
      147,  377,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  377,

      377,  377,  377,  377,  377,  377,  377,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  377,  377,  377,  377,  377,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  377,  377,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  377,  381,  381,  381,  381,    0,  377,  377,  377,
      377,  377,  377
    } ;

static yyconst flex_uint16_t yy_nxt[712] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   29,   29,   29,   29,   29,   29,
       29,   30,   29,   29,   29,   29,   29,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   29,
       43,   29,   44,   29,   29,   45,   29,   46,   47,   48,
       49,   50,   51,   29,   29,   29,   52,   53,   54,   55,
       56,   58,   56,   58,   61,   57,   65,   68,   71,   92,
       76,   73,   77,   77,   77,   77,   77,   77,   77,   77,

       77,   87,   88,  192,   78,   72,   74,   75,   66,   79,
       81,  193,   82,   83,   83,   83,   83,   83,   83,   82,
       82,  123,   80,   90,   91,  124,   69,   62,   81,  127,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   98,
       85,   99,  100,  103,  108,  105,  112,  106,   61,  101,
      117,  118,  104,  113,  109,  102,  107,  110,  121,  129,
      119,  129,  140,  120,  130,  122,  131,   85,  131,   68,
       58,   63,   58,  138,  138,  143,  128,  139,  141,  141,
      194,  224,  195,  129,   68,  129,  142,  184,  130,  225,
      144,   62,  145,  145,  145,  145,  145,  145,  145,  145,

      145,  149,  181,  159,  185,   62,   61,  160,   69,  376,
      256,  150,  161,  182,   69,  186,  149,  198,  257,  199,
      132,  133,  200,   69,  162,  134,  150,  135,  138,  138,
      187,  377,  139,  377,  375,  136,  374,  137,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  373,  233,   62,
      234,  372,  371,  235,  236,  147,  153,  153,  153,  153,
      153,  153,  153,  153,  153,   82,   82,   82,   82,   82,
       82,   82,   82,   82,  370,  369,  147,  154,  154,  154,
      154,  154,  154,  154,   82,   82,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  131,  285,  131,  131,  368,

      131,  155,  155,  155,  155,  141,  141,  149,  205,  205,
      286,  367,  206,  142,  366,  365,  364,  150,  207,  207,
      155,  155,  155,  155,  155,  155,  208,  209,  363,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  205,  205,  132,
      133,  206,  132,  133,  134,   62,  135,  134,  362,  135,
      361,  360,  359,  358,  136,   69,  137,  136,  210,  137,
      210,  357,  356,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  154,  154,  154,  154,  154,  154,  154,   82,
       82,  205,  205,  355,   62,  206,  207,  207,  207,  207,

      354,  353,  352,  351,  208,  209,  208,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  291,  350,  292,  349,  348,
      293,  294,  347,  346,  345,  344,  343,  342,   62,  341,
      340,  339,  338,   69,  337,   69,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  295,   60,   60,   60,   67,   67,   67,   84,
       84,  148,  148,  148,  151,  151,  151,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,

      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  290,  289,  288,  287,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  262,  261,  260,  259,
      258,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      232,  231,  230,  229,  228,  227,  226,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  152,  212,
      204,  203,  202,  201,  197,  196,  191,  190,  189,  188,
      183,  180,  179,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  168,  167,  166,  165,  164,  163,  158,
      157,  156,  152,  126,  125,  116,  115,  114,  111,   97,
       96,   95,   94,   93,   89,   70,   64,   63,   59,  377,
        3,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377
    } ;

static yyconst flex_int16_t yy_chk[712] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    5,    2,    5,    8,    2,   11,   12,   16,  381,
       19,   18,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   25,   25,  124,   20,   16,   18,   18,   11,   20,
       21,  124,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   49,   20,   27,   27,   49,   12,    8,   22,   53,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   37,
       21,   37,   38,   39,   41,   40,   43,   40,   60,   38,
       47,   47,   39,   43,   41,   38,   40,   41,   48,   56,
       47,   56,   62,   47,   56,   48,   57,   21,   57,   67,
       58,   57,   58,   61,   61,   69,   53,   61,   68,   68,
      125,  169,  125,  129,  142,  129,   68,  118,  129,  169,
       76,   60,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   78,  116,   96,  118,   62,  139,   96,   67,  375,
      198,   78,   96,  116,   69,  119,  148,  133,  198,  133,
       57,   57,  133,  142,   96,   57,  148,   57,  138,  138,
      119,  211,  138,  211,  373,   57,  369,   57,   77,   77,
       77,   77,   77,   77,   77,   77,   77,  363,  178,  139,
      178,  360,  358,  178,  178,   77,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   82,   82,   82,   82,   82,
       82,   82,   82,   82,  357,  356,   77,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   85,   85,   85,   85,
       85,   85,   85,   85,   85,  130,  243,  130,  131,  354,

      131,   85,   85,   85,   85,  141,  141,  149,  140,  140,
      243,  353,  140,  141,  352,  350,  344,  149,  143,  143,
       85,   85,   85,   85,   85,   85,  143,  144,  343,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  205,  205,  130,
      130,  205,  131,  131,  130,  140,  130,  131,  342,  131,
      341,  340,  336,  335,  130,  143,  130,  131,  147,  131,
      147,  334,  333,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  206,  206,  332,  205,  206,  207,  207,  208,  208,

      331,  330,  329,  328,  207,  209,  208,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  210,  210,  210,  210,
      210,  210,  210,  210,  210,  249,  320,  249,  318,  317,
      249,  249,  316,  313,  312,  311,  310,  309,  206,  308,
      307,  306,  304,  207,  303,  208,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  300,  298,  297,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      282,  281,  249,  378,  378,  378,  379,  379,  379,  380,
      380,  382,  382,  382,  383,  383,  383,  279,  278,  277,
      276,  273,  272,  271,  270,  267,  266,  265,  264,  262,

      261,  260,  259,  258,  257,  256,  255,  254,  253,  251,
      250,  248,  246,  245,  244,  242,  241,  240,  239,  238,
      236,  235,  234,  233,  231,  230,  229,  226,  225,  224,
      223,  220,  217,  216,  215,  214,  204,  203,  202,  200,
      199,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      177,  175,  174,  173,  172,  171,  170,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  151,  150,
      137,  136,  135,  134,  132,  126,  123,  122,  121,  120,
      117,  115,  114,  113,  111,  110,  109,  108,  107,  106,

      105,  104,  103,  102,  101,  100,   99,   98,   97,   93,
       91,   87,   79,   51,   50,   46,   45,   44,   42,   36,
       35,   34,   32,   30,   26,   15,   10,    9,    7,    3,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[125] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 
    1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "front/lexical.l"
#line 2 "front/lexical.l"
#include "front-com.h"

/*function declaration*/
int next_number(char **str, int base);
char register_literal(const char *str);
char* register_string(const char *str);
char* register_id(const char *text);
int fileno(FILE *stream);
void increase_actionlevel();
void decrease_actionlevel();

#define YY_NO_UNPUT
#define YY_NO_INPUT

/*lexerr*/
static int yycolumn = 1;

extern YYLTYPE yylloc;

#define YY_USER_ACTION do { \
		yylloc.first_line = yylloc.last_line = yylineno; \
		yylloc.first_column = yycolumn; \
		yylloc.last_column = yycolumn+yyleng-1; \
		yycolumn += yyleng; \
	} while(0);

#define YY_DECL int next_token(void)

static int symbol(int syntaxval);
static int qulfr(int token);
static int type(int rawtoken, int typeinfo);
static int num(int specval);
static int reg(int syntaxval);
static int relop(int token);
static int equop(int token);

#line 821 "front/lexical.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 56 "front/lexical.l"

#line 1044 "front/lexical.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 378 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 631 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "front/lexical.l"
{return symbol(MACRO_DEFINE);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "front/lexical.l"
{return symbol(MACRO_UNDEF);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "front/lexical.l"
{return symbol(MACRO_IF);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "front/lexical.l"
{return symbol(MACRO_ELIF);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "front/lexical.l"
{return symbol(MACRO_ELSE);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "front/lexical.l"
{return symbol(MACRO_ENDIF);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "front/lexical.l"
{return symbol(MACRO_LINE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "front/lexical.l"
{return symbol(MACRO_WARNING);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "front/lexical.l"
{return symbol(MACRO_ERROR);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "front/lexical.l"
{return symbol(STRINGIFY);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "front/lexical.l"
{return symbol(CONCAT);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "front/lexical.l"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "front/lexical.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "front/lexical.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "front/lexical.l"
{return symbol(VA_ARGS);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "front/lexical.l"
{return symbol(DEFINED);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 "front/lexical.l"
{return symbol(ASSIGNOP);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 "front/lexical.l"
{return symbol(EQ);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 "front/lexical.l"
{return symbol(NE);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 77 "front/lexical.l"
{return relop(LT);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 78 "front/lexical.l"
{return relop(LE);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 79 "front/lexical.l"
{return relop(GT);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 80 "front/lexical.l"
{return relop(GE);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "front/lexical.l"
{return symbol(LSHIFT);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 "front/lexical.l"
{return symbol(RSHIFT);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "front/lexical.l"
{return symbol(LSHIFTE);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "front/lexical.l"
{return symbol(RSHIFTE);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "front/lexical.l"
{return symbol(ADD);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "front/lexical.l"
{return symbol(SUB);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "front/lexical.l"
{return symbol(MULT);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "front/lexical.l"
{return symbol(DIV);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "front/lexical.l"
{return symbol(MOD);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "front/lexical.l"
{return symbol(INC);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "front/lexical.l"
{return symbol(DEC);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "front/lexical.l"
{return equop(ADDE);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 95 "front/lexical.l"
{return equop(SUBE);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "front/lexical.l"
{return equop(MULTE);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 97 "front/lexical.l"
{return equop(DIVE);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 98 "front/lexical.l"
{return equop(MODE);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "front/lexical.l"
{return equop(ANDE);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "front/lexical.l"
{return equop(ORE);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "front/lexical.l"
{return equop(XORE);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "front/lexical.l"
{return symbol(AND);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "front/lexical.l"
{return symbol(OR);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "front/lexical.l"
{return symbol(XOR);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "front/lexical.l"
{return symbol(NOT);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "front/lexical.l"
{return symbol(LAND);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "front/lexical.l"
{return symbol(LOR);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "front/lexical.l"
{return symbol(LNOT);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 110 "front/lexical.l"
{return symbol(SIZEOF);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "front/lexical.l"
{return symbol(LP);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 113 "front/lexical.l"
{return symbol(RP);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "front/lexical.l"
{return symbol(LB);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 115 "front/lexical.l"
{return symbol(RB);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "front/lexical.l"
{increase_actionlevel();return symbol(LC);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "front/lexical.l"
{return symbol(RC);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "front/lexical.l"
{return symbol(DOT);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "front/lexical.l"
{return symbol(PTR);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "front/lexical.l"
{return symbol(COMMA);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "front/lexical.l"
{return symbol(QOP);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 122 "front/lexical.l"
{return symbol(COLON);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 123 "front/lexical.l"
{return symbol(SEMI);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 124 "front/lexical.l"
{return symbol(ELLIPSIS);}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 125 "front/lexical.l"
{/*do nothing*/}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 126 "front/lexical.l"
{return symbol(NEWLINE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 127 "front/lexical.l"
{return symbol(SPACE);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "front/lexical.l"
{return type(VOID, MAKE_WORD(SpecTypeVoid, false));}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "front/lexical.l"
{return type(BOOL, MAKE_WORD(SpecTypeUint8, false));}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "front/lexical.l"
{return type(CHAR, MAKE_DWORD2(CombineTypeChar, MAKE_WORD(SpecTypeInt8, true)));}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 132 "front/lexical.l"
{return type(SHORT, MAKE_DWORD2(CombineTypeShort, MAKE_WORD(SpecTypeInt16, true)));}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "front/lexical.l"
{return type(INT, MAKE_DWORD2(CombineTypeInt, MAKE_WORD(SpecTypeInt32, true)));}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 134 "front/lexical.l"
{return type(LONG, MAKE_DWORD2(CombineTypeLong, MAKE_WORD(SpecTypeInt32, true)));}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 135 "front/lexical.l"
{return type(SIGNED, MAKE_DWORD2(CombineTypeSigned, MAKE_WORD(SpecTypeInt32, true)));}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 136 "front/lexical.l"
{return type(UNSIGNED, MAKE_DWORD2(CombineTypeUnsigned, MAKE_WORD(SpecTypeUint32, true)));}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 137 "front/lexical.l"
{return type(FLOAT, MAKE_WORD(SpecTypeFloat32, false));}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 138 "front/lexical.l"
{return type(DOUBLE, MAKE_DWORD2(CombineTypeDouble, MAKE_WORD(SpecTypeFloat64, true)));}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 139 "front/lexical.l"
{return type(INT8T, MAKE_WORD(SpecTypeInt8, false));}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 140 "front/lexical.l"
{return type(INT16T, MAKE_WORD(SpecTypeInt16, false));}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 141 "front/lexical.l"
{return type(INT32T, MAKE_WORD(SpecTypeInt32, false));}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 142 "front/lexical.l"
{return type(INT64T, MAKE_WORD(SpecTypeInt64, false));}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 143 "front/lexical.l"
{return type(UINT8T, MAKE_WORD(SpecTypeUint8, false));}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 144 "front/lexical.l"
{return type(UINT16T, MAKE_WORD(SpecTypeUint16, false));}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 145 "front/lexical.l"
{return type(UINT32T, MAKE_WORD(SpecTypeUint32, false));}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 146 "front/lexical.l"
{return type(UINT64T, MAKE_WORD(SpecTypeUint64, false));}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 147 "front/lexical.l"
{return type(SIZET, MAKE_WORD(SpecTypeUint32, false));}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 "front/lexical.l"
{return type(UINTPTRT, MAKE_WORD(SpecTypeUint32, false));}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 149 "front/lexical.l"
{return type(OFFT, MAKE_WORD(SpecTypeInt32, false));}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 151 "front/lexical.l"
{return symbol(ENUM);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 152 "front/lexical.l"
{return symbol(UNION);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 153 "front/lexical.l"
{return symbol(STRUCT);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 154 "front/lexical.l"
{return symbol(NIL);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "front/lexical.l"
{return symbol(TRUE);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 156 "front/lexical.l"
{return symbol(FALSE);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "front/lexical.l"
{return symbol(IF);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 159 "front/lexical.l"
{return symbol(ELSE);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 160 "front/lexical.l"
{return symbol(DO);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 161 "front/lexical.l"
{return symbol(WHILE);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 162 "front/lexical.l"
{return symbol(FOR);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 163 "front/lexical.l"
{return symbol(RETURN);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 164 "front/lexical.l"
{return symbol(SWITCH);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 165 "front/lexical.l"
{return symbol(CASE);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 166 "front/lexical.l"
{return symbol(BREAK);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 167 "front/lexical.l"
{return symbol(DEFAULT);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 168 "front/lexical.l"
{return symbol(GOTO);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 170 "front/lexical.l"
{return qulfr(QulfrTypedef);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 171 "front/lexical.l"
{return qulfr(QulfrExtern);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 172 "front/lexical.l"
{return qulfr(QulfrStatic);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 173 "front/lexical.l"
{return qulfr(QulfrAuto);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 174 "front/lexical.l"
{return qulfr(QulfrRegister);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 176 "front/lexical.l"
{return qulfr(QulfrConst);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 177 "front/lexical.l"
{return qulfr(QulfrVolatile);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 179 "front/lexical.l"
{return num('i');}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 180 "front/lexical.l"
{return num('x');}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 181 "front/lexical.l"
{return num('o');}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 182 "front/lexical.l"
{return num('f');}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 184 "front/lexical.l"
{
						
						//yydbg(yylineno, yycolumn-yyleng, yyleng, ErrorInvalidNUM);
						return symbol(NUM);
					}
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 189 "front/lexical.l"
{return reg(LITERAL);}
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 190 "front/lexical.l"
{return reg(STRING);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 191 "front/lexical.l"
{return reg(ID);}
	YY_BREAK
case 120:
/* rule 120 can match eol */
YY_RULE_SETUP
#line 192 "front/lexical.l"
{/*do nothing*/}
	YY_BREAK
case 121:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 193 "front/lexical.l"
{/*do nothing*/}
	YY_BREAK
case 122:
/* rule 122 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 194 "front/lexical.l"
{
						
						extern int curlineno;
						logd("%d: error type A: invalid comment\n", curlineno);
					}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 199 "front/lexical.l"
{
						//FIXME
						//yydbg(yylineno, yycolumn-yyleng, yyleng, ErrorUnknownToken);
					}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 204 "front/lexical.l"
ECHO;
	YY_BREAK
#line 1756 "front/lexical.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 378 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 378 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 377);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 204 "front/lexical.l"



static int qulfr(int token) {
	node_t *pnd = new_node();
	pnd->token = TypeQulfr;
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	pnd->cv.ex = token;
	yylval.pnd = pnd;
	return TypeQulfr;
}

static int equop(int token) {
	node_t *pnd = new_node();
	pnd->token = token;
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	yylval.pnd = pnd;
	return EQUOP;
}

static int relop(int token) {
	node_t *pnd = new_node();
	pnd->token = token;
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	yylval.pnd = pnd;
	return RELOP;
}

static int symbol(int syntaxval) {
	node_t *pnd = new_node();
	pnd->token = syntaxval;
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	yylval.pnd = pnd;
	return syntaxval;
}

static int type(int token, int typeinfo) {
	/* +----------------+--------+--------+
	 * |       ct       |   bt   |   0/1  |
	 * +----------------+--------+--------+
	 */
	node_t *pnd = new_node();
	pnd->token = TYPE;
	pnd->production = token;
	pnd->cv.t = typeinfo;
	pnd->dt = convert_btype_to_pointer(WORD_PART1(typeinfo));
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	yylval.pnd = pnd;
	return TYPE;
}

static int num(int numtype) {
	char *pstr = yytext;
	node_t *pnd = new_node();
	pnd->token = NUM;
	pnd->dt = new_spec();//FIXME:overflow of int
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	pnd->cv.str = sformat("%s", yytext);
	yylval.pnd = pnd;

	switch(numtype) {
		case 'i':
			pnd->cv.t = 'i';
			pnd->cv.i = next_number(&pstr, 10);
			break;
		case 'o':
			pstr++;
			pnd->cv.t = 'o';
			pnd->cv.i = next_number(&pstr, 8);
			break;
		case 'x':
			pstr+=2;
			pnd->cv.t = 'x';
			pnd->cv.i = next_number(&pstr, 16);
			break;
		case 'f':
			pnd->cv.t = SpecTypeFloat32;
			pnd->cv.f = atof(pstr);
			break;
	}
	return NUM;
}

static int reg(int syntaxval) {
	node_t *pnd = new_node();
	pnd->token = syntaxval;
	pnd->lineno = yylineno;
	pnd->column = yycolumn;
	yylval.pnd = pnd;

	switch(syntaxval)
	{
	case LITERAL:
		pnd->lrv = SpecRvalue;
		pnd->dt = convert_btype_to_pointer(SpecTypeInt8);
		pnd->cv.str = sformat("%s", yytext);
		pnd->cv._8 = register_literal(yytext);
		break;
	case STRING:
		pnd->lrv = SpecLvalue;
		pnd->dt = convert_btype_to_pointer(SpecTypeString);
		pnd->cv.str = register_string(yytext);
		break;
	case ID:
		pnd->cv.id = register_id(yytext);
		break;
	}
	return syntaxval;
}

int next_number(char **str, int base) {
	int retval = 0;
	/* 0xff,088,255 at most 4 nums */
	for(int i = 0; *str[0]; i++)
	{
		bool cur_valid = false;
		int ch = *(str[0]);
		str[0]++;
		switch(base)
		{
			case 16:
				if(('0' <= ch && ch <= '9')
					|| ('a' <= ch && ch <= 'f')
					|| ('A' <= ch && ch <= 'F'))
				{
					if('0' <= ch && ch <= '9')
						retval = retval*16+ch-'0';
					else if('a' <= ch && ch <= 'f')
						retval = retval*16+ch+10-'a';
					else if('A' <= ch && ch <= 'F')
						retval = retval*16+ch+10-'A';
					cur_valid = true;
				}
				break;
			case 1:case 2:case 3:case 4:case 5:
			case 6:case 7:case 8:case 9:case 10:
				if('0' <= ch && ch < '0' + base)
				{
					retval = retval*base+ch-'0';
					cur_valid = true;
				}
				break;
		}
		if(!cur_valid) {str[0]--;break;}
	}
	return retval;
}

char register_literal(const char *str) {
	if(str[1] == '\\') {
		char *p = (char *)&str[2];
		switch(str[2]){
			case '\\':return '\\';
			case 'n' :return '\n';
			case 'r' :return '\r';
			case 't' :return '\t';
			case 'b' :return '\b';
			case 'x' :
			case 'X' :return next_number(&p, 16);break;
			case '0' :return next_number(&p, 8);break;
			default  :return str[2];
		}
	}else{
		return str[1];
	}
}

/* return value is the start position of registered string */
char* register_string(const char *str) {
	int buf_ptr = 0;
	char *buf = malloc(strlen(str) + 1);
	char *p = (char *)str;
	bool in_str = true;
	while(*(++p)) //since the first char is always `"`
	{
		if(*p == '"') {in_str = !in_str;continue;}
		if(!in_str)	continue;
		if(*p != '\\')
			buf[buf_ptr ++] = *p;
		else
			switch(*(++p))
			{
				case '\\':buf[buf_ptr ++] = '\\';break;
				case 'n' :buf[buf_ptr ++] = '\n';break;
				case 'r' :buf[buf_ptr ++] = '\r';break;
				case 't' :buf[buf_ptr ++] = '\t';break;
				case 'b' :buf[buf_ptr ++] = '\b';break;
				case 'x' :
				case 'X' :p++;buf[buf_ptr ++] = next_number(&p, 16);p--;break;
				case '0' :p++;buf[buf_ptr ++] = next_number(&p, 8);p--;break;
				default  :buf[buf_ptr ++] = *p;break;
			}
	}
	buf[buf_ptr] = 0;
	return buf;
}

char* register_id(const char *text) {
	int len = strlen(text) + 1;
	char *buf = malloc(len);
	strcpy(buf, text);
	return buf;
}

int swallow_space() {
	int lexval = -1;
	do{lexval = next_token();}while(lexval == SPACE);
	return lexval;
}

int swallow_blank_and_newline() {
	int lexval = -1;
	do{lexval = next_token();}while(lexval == NEWLINE || lexval == SPACE);
	return lexval;
}

bool check_duparg_in_macro(macro_arg_t *arg, size_t len) {
	for(int i = 0; i < len; i++) {
		for(int j = i + 1; j < len; j++) {
			if(arg[j].id && strcmp(arg[i].id, arg[j].id) == 0) {
				eprintf("duplicate argument '%s' in macro.\n", arg[i].id);
				return true;
			}
		}
	}
	return false;
}

int find_arg_in_macro(macro_arg_t *argv, size_t len, char *id) {
	for(int i = 0; i < len; i++) {
		if(argv[i].id && strcmp(argv[i].id, id) == 0) {
			return i;
		}
	}
	return -1;
}

vec_t macro_buffer;

macro_t *find_macro_by_id(char *id) {
	if(!id) return NULL;
	macro_t *ma = macro_buffer.p;
	for(int i = vector_size(&macro_buffer) - 1; i >= 0; i--) {
		if(ma[i].id && strcmp(ma[i].id, id) == 0){
			return &ma[i];
		}
	}
	return NULL;
}

bool match_const_macro_exp() {
	//+, -, *, /, %, <<, >>,
	//<, >, ==
	//&, |, ~, ^, &&, ||, !
	//defined(), ','
	//warning: no floating, no zero division
	static int priority[] = {
		[LP] = 1, [RP] = 1,
		[LNOT] = 2, [NOT] = 2, [DEFINED] = 2,
		[MULT] = 3, [DIV] = 3, [MOD] = 3,
		[LSHIFT] = 4, [RSHIFT] = 4,
		[LT] = 5, [LE] = 5, [GE] = 5, [GT] = 5,
		[EQ] = 6, [NE] = 6,
		[AND] = 7, [XOR] = 8, [OR] = 9, [LAND] = 10, [LOR] = 11,
		[QOP] = 12, [COLON] = 12, [COMMA] = 13,
	};

	vec_t opstack, outstack;
	vector_init(&opstack, sizeof(node_t *));
	vector_init(&outstack, sizeof(int));
	if(swallow_space() == NEWLINE) {
		//TODO:report error
		return false;
	}else{
		vector_push(&opstack, &(yylval.pnd));
	}

	while(vector_size(&opstack)) {
	}
}

int match_macro() {
	//FIXME:handle error state
	static int mmt[11][MacroTokenSize] = {
		     /*ID LP RP , ... id.## #  \n ' 'other EOF*/
		[0] = { 1,10,10,10,10,10,10,10,10, 0,10, 10},
		[1] = { 8, 2, 8, 8, 8, 8, 8, 8, 8, 1, 8,  9},
		[2] = { 3,10, 5,10, 4,10,10,10,10, 2,10, 10},
		[3] = {10,10, 5, 2, 4,10,10,10,10, 3,10, 10},
		[4] = {10,10, 5,10,10,10,10,10,10, 4,10, 10},
		[5] = { 8, 8, 8, 8, 8, 8, 8, 6, 8, 5, 8,  9},
		[6] = { 8,10,10,10,10,10,10,10,10, 6,10, 10},
		[7] = { 8, 8, 8, 8, 8, 8,10,10,10, 7, 8,  8},
		[8] = { 8, 8, 8, 8, 8, 8, 7, 6, 9, 8, 8,  9},
		[9] = {10,10,10,10,10,10,10,10,10, 9,10, 10},//acc
		[10]= {10,10,10,10,10,10,10,10,10,10,10, 10},//err
	};
	//register .. or args... in state 4
	//register id in state 5
	macro_t macro;
	size_t argc = 0, mtlen = 0;
	int cur_state = 0, last_state = 0, lexval = 0, last_mtt = -1;
	node_t *lastnd = NULL;
	macro_token_t *mt = NULL;
	macro_arg_t *argv = NULL;
	while(cur_state != 9 && cur_state != 10) {
		int tokval = 0;
		lexval = swallow_space();
		switch(lexval) {
			case ID:        tokval = MacroID;        break;
			case LP:        tokval = MacroLP;        break;
			case RP:        tokval = MacroRP;        break;
			case COMMA:     tokval = MacroCOMMA;     break;
			case ELLIPSIS:  tokval = MacroELLIPSIS;  break;
			case CONCAT:    tokval = MacroCONCAT;    break;
			case STRINGIFY: tokval = MacroSTRINGIFY; break;
			case NEWLINE:   tokval = MacroNEWLINE;   break;
			case SPACE:     tokval = MacroSPACE;     break;
			case 0://EOF
				tokval = MacroEOF;
				break;
			default:        tokval = MacroOther;     break;
		}

		cur_state = mmt[cur_state][tokval];
		logd("switch state: %d --> %d\n", last_state, cur_state);
		logd("triggered by %d, '%s'\n", tokval, lexval?yytext:"EOF");

		int index = 0, mtt = 0, cat_index = 0;
		switch(cur_state) {
		case 1:
			macro.id = yylval.pnd->cv.id;
			argv = get_memory_pointer();
			break;
		case 2:
			if(last_state == 3) {
				//ID
				argv[argc].token = MacroID;
				argv[argc].id = lastnd->cv.id;
				argc ++;
			}
			break;
		case 4:
			if(last_state == 2) {
				//...
				argv[argc].token = MacroELLIPSIS;
				argv[argc].id = NULL;
				argc ++;
			}else if(last_state == 3){
				//args...
				argv[argc].token = MacroIDELLIPSIS;
				argv[argc].id = lastnd->cv.id;
				argc ++;
			}else{
				logw("check here.\n");
			}
			break;
		case 5:
			macro.bt = MacroArgs;
			if(last_state == 3) {
				//ID
				argv[argc].token = MacroID;
				argv[argc].id = lastnd->cv.id;
				argc ++;
			}
			argv = require_memory(sizeof(macro_arg_t) * argc);
			if(check_duparg_in_macro(argv, argc))
				cur_state = 10;//err
			else
				mt = get_memory_pointer();
			break;
		case 6:
			lexval = swallow_space();
			if(lexval != ID) {
				//err
				logd("lexval=%d, should be ID=%d\n", lexval, ID);
				cur_state = 10;
			}else{
				char *cur_id = yylval.pnd->cv.id;
				int index = find_arg_in_macro(argv, argc, cur_id);
				if(index == -1) {
					//err
					cur_state = 10;
					logd("fail to find arg '%s'\n", cur_id);
				}else{
					mt[mtlen].mtt = MacroTokenStringify;
					mt[mtlen].i = index;
					mt[mtlen].pnd = yylval.pnd;
					last_mtt = MacroTokenStringify;
					mtlen ++;
					cur_state = 8;
				}
			}
			break;
		case 7:
			mtt = 0;
			if(last_mtt == MacroTokenConcatTJ
			|| last_mtt == MacroTokenConcatIJ)
				cat_index = mtlen ++;
			else
				cat_index = mtlen - 1;
			if(lastnd->token == ID && (index = find_arg_in_macro(argv, argc, lastnd->cv.id)) != -1){
				//this is arg
				mtt = mtt | 0x2;
				mt[cat_index].i = index;
			}else{
				//common token
				mt[mtlen].mtt = MacroTokenCommon;
				mt[mtlen].pnd = lastnd;
				mtlen ++;
			}

			do{
				lexval = next_token();
			}while(lexval == SPACE || lexval == CONCAT);
			if(yylval.pnd->token == ID && (index = find_arg_in_macro(argv, argc, yylval.pnd->cv.id)) != -1){
				//this is arg
				mtt = mtt | 0x1;
				mt[cat_index].j = index;
			}else{
				mt[mtlen].mtt = MacroTokenCommon;
				mt[mtlen].pnd = yylval.pnd;
				mtlen ++;
			}
			mt[cat_index].mtt = mtt;
			last_mtt = mtt;
			cur_state = 8;
			break;
		case 8:
			//store all token
			if(last_state == 1){
				macro.bt = MacroNormal;
				require_memory(0);
				mt = get_memory_pointer();
				mt[mtlen].mtt = MacroTokenCommon;
				mt[mtlen].pnd = yylval.pnd;
				last_mtt = MacroTokenCommon;
				mtlen ++;
			}else if(last_state == 5 || last_state == 8){
				//store
				int index = 0;
				if(yylval.pnd->token == ID
				&& (index = find_arg_in_macro(argv, argc, yylval.pnd->cv.id)) != -1){
					mt[mtlen].mtt = MacroTokenArg;
					mt[mtlen].i = index;
					mt[mtlen].pnd = yylval.pnd;
					last_mtt = MacroTokenArg;
					mtlen ++;
				}else{
					mt[mtlen].mtt = MacroTokenCommon;
					mt[mtlen].pnd = yylval.pnd;
					last_mtt = MacroTokenCommon;
					mtlen ++;
				}
			}else if(last_state == 6){//do nothing
			}else if(last_state == 7){//do nothing
			}
			break;
		case 9:
			mt = require_memory(mtlen * sizeof(macro_token_t));
			//accept
			break;
		}

		last_state = cur_state;
		lastnd = yylval.pnd;
	}
	if(!bpool_state_close()) require_memory(0);

	if(cur_state == 10) {
		macro.bt = MacroBad;
		//TODO:report error reason
	}

	if(lexval == NEWLINE) swallow_blank_and_newline();

	macro.argc = argc;
	macro.argv = argv;
	macro.mtlen = mtlen;
	macro.mt = mt;
	vector_push(&macro_buffer, &macro);

	return lexval;
}

char *macro_format(macro_t *macro) {
	if(!macro) return NULL;
	//format arg
	char *token_format(node_t *);
	char *buf = get_memory_pointer();
	sprintf(buf, "#define %s(", macro->id);
	for(int i = 0; i < macro->argc; i++) {
		if(macro->argv[i].token == MacroID)
			sprintf(buf + strlen(buf), "%s", macro->argv[i].id);
		else if(macro->argv[i].token == MacroELLIPSIS) {
			sprintf(buf + strlen(buf), "...");
		}else if(macro->argv[i].token == MacroIDELLIPSIS){
			sprintf(buf + strlen(buf), "%s...", macro->argv[i].id);
		}

		if(i != macro->argc - 1)
			sprintf(buf + strlen(buf), ", ");
	}
	sprintf(buf + strlen(buf), ") ");
	for(int i = 0; i < macro->mtlen; i++) {
		char *ss[] = {"TT", "TJ", "IT", "IJ", "", "s.", "@"};
		printf("%s", ss[macro->mt[i].mtt]);
		if(macro->mt[i].mtt == MacroTokenCommon)
			printf("%s ", token_format(macro->mt[i].pnd));
		else
			printf(" ");
	}
	printf("\n");
	for(int i = 0; i < macro->mtlen; i++) {
		//logw("i:%d, mtt:%d\n", i, macro->mt[i].mtt);
		//logw("%p\n", &macro->mt[i].mtt);
		if(macro->mt[i].mtt == MacroTokenArg) {
			sprintf(buf + strlen(buf), "@%d:%s ", macro->mt[i].i, token_format(macro->mt[i].pnd));
		}else if(macro->mt[i].mtt == MacroTokenStringify){
			sprintf(buf + strlen(buf), "#%d:%s ", macro->mt[i].i, token_format(macro->mt[i].pnd));
		}else if(macro->mt[i].mtt == MacroTokenConcatTT){
			if(i + 2 >= macro->mtlen || macro->mt[i + 2].mtt >= 4){
				sprintf(buf + strlen(buf), "%s ## %s ", token_format(macro->mt[i + 1].pnd), token_format(macro->mt[i + 2].pnd));
				i += 2;
			}else{
				sprintf(buf + strlen(buf), "%s ## ", token_format(macro->mt[i + 1].pnd));
				i ++;
			}
		}else if(macro->mt[i].mtt == MacroTokenConcatTJ){
			if(i + 2 >= macro->mtlen || macro->mt[i + 2].mtt >= 4){
				sprintf(buf + strlen(buf), "%s ## @%d:%s ",
					token_format(macro->mt[i + 1].pnd),
					macro->mt[i].j,
					macro->argv[macro->mt[i].j].id);
				i ++;
			}else{
				sprintf(buf + strlen(buf), "%s ## ",
					token_format(macro->mt[i + 1].pnd));
				i ++;
			}
		}else if(macro->mt[i].mtt == MacroTokenConcatIT){
			if(i + 1 >= macro->mtlen || macro->mt[i + 1].mtt >= 4){
				sprintf(buf + strlen(buf), "@%d:%s ## %s ",
					macro->mt[i].i, macro->argv[macro->mt[i].i].id,
					token_format(macro->mt[i + 1].pnd));
				i ++;
			}else{
				sprintf(buf + strlen(buf), "@%d:%s ## ",
					macro->mt[i].i, macro->argv[macro->mt[i].i].id);
			}
		}else if(macro->mt[i].mtt == MacroTokenConcatIJ){
			if(i + 1 >= macro->mtlen || macro->mt[i + 1].mtt >= 4){
				sprintf(buf + strlen(buf), "@%d:%s ## @%d:%s ",
					macro->mt[i].i, macro->argv[macro->mt[i].i].id,
					macro->mt[i].j, macro->argv[macro->mt[i].j].id);
			}else{
				sprintf(buf + strlen(buf), "@%d:%s ## ",
					macro->mt[i].i, macro->argv[macro->mt[i].i].id);
			}
		}else if(macro->mt[i].mtt == MacroTokenCommon){
			sprintf(buf + strlen(buf), "%s ", token_format(macro->mt[i].pnd));
		}else{
			logw("check it! mtt=%d\n", macro->mt[i].mtt);
		}
	}
	buf = require_memory(strlen(buf) + 1);
	return buf;
}

int yylex() {
	int lexval = swallow_blank_and_newline();
	switch(lexval) {
	case MACRO_DEFINE:
		lexval = match_macro();
		break;
	case ID:
		if(find_macro_by_id(yylval.pnd->cv.id)){
			//TODO
		}
		break;
	case VA_ARGS:
		yylval.pnd = new_node();
		yylval.pnd->token = ID;
		yylval.pnd->lineno = yylineno;
		yylval.pnd->column = yycolumn;
		yylval.pnd->cv.id = "__VA_ARGS__";
		break;
	default:
		break;
	}
	return lexval;
}

void tokenize_from_string(const char *string) {
	void *buffer_state = yy_scan_string(string);
	yy_switch_to_buffer(buffer_state);
	while(yylex() > 0);
	yylex_destroy();
}

int init_lexical() {
	vector_init(&macro_buffer, sizeof(macro_t));
#ifdef __DEBUG__
	/* unit test of register_string */
	UNIT_TEST_START;
	
	struct {
		char *sample, *ans;
	}test_macro_string[] = {
		{"#define macro a e + - extern int * /",
		 "#define macro() a e ADD SUB extern INT MULT DIV "},
		{"#define macro a b c \\\n d e\n",
		 "#define macro() a b c d e "},
		{"#define macro() a b c \\\n d e\n",
		 "#define macro() a b c d e "},
		{"#define macro() a b c \\/\n d e\n",
		 "#define macro() a b c DIV "},
		{"#define macro(aa) aa vv dd \\/\n d e\n",
		 "#define macro(aa) @0:aa vv dd DIV "},
		{"#define macro(aa) a vv dd \\/\n d e\n",
		 "#define macro(aa) a vv dd DIV "},
		{"#define macro(aa,vv,dd) aa vv dd \\/\n d e\n",
		 "#define macro(aa, vv, dd) @0:aa @1:vv @2:dd DIV "},
		{"#define macro(a,b,c) # a vv dd \\/",
		 "#define macro(a, b, c) #0:a vv dd DIV "},
		{"#define macro(a,b,c) # a",
		 "#define macro(a, b, c) #0:a "},
		{"#define macro(a,b,c) # a b ## c",
		 "#define macro(a, b, c) #0:a @1:b ## @2:c "},
		{"#define macro(a,b) a##b",
		 "#define macro(a, b) @0:a ## @1:b "},
		{"#define macro(a,b,c)  d## vv dd ",
		 "#define macro(a, b, c) d ## vv dd "},
		{"#define macro(a,b,c)  a## vv dd ",
		 "#define macro(a, b, c) @0:a ## vv dd "},
		{"#define macro(a,b,c)  vv## c dd ",
		 "#define macro(a, b, c) vv ## @2:c dd "},
		{"#define macro(a,b,c)  a## c dd ",
		 "#define macro(a, b, c) @0:a ## @2:c dd "},
		{"#define macro(a,b,c)  vv## vv##vv dd ",
		 "#define macro(a, b, c) vv ## vv ## vv dd "},
		{"#define macro(a,b,c)  vv## vv##a dd ",
		 "#define macro(a, b, c) vv ## vv ## @0:a dd "},
		{"#define macro(a,b,c)  vv## a##vv dd ",
		 "#define macro(a, b, c) vv ## @0:a ## vv dd "},
		{"#define macro(a,b,c)  a## vv##vv dd ",
		 "#define macro(a, b, c) @0:a ## vv ## vv dd "},
		{"#define macro(a,b,c)  a## b##vv dd ",
		 "#define macro(a, b, c) @0:a ## @1:b ## vv dd "},
		{"#define macro(a,b,c)  vv ##a## b vv dd ",
		 "#define macro(a, b, c) vv ## @0:a ## @1:b vv dd "},
		{"#define macro(a,b,c)  c ##a## b vv dd ",
		 "#define macro(a, b, c) @2:c ## @0:a ## @1:b vv dd "},
		{"#define macro(a,b,c)  vv ##vv## a## vv##b##c##as##q vv dd ",
		 "#define macro(a, b, c) vv ## vv ## @0:a ## vv ## @1:b ## @2:c ## as ## q vv dd "},
		{"#define macro(a,b,c)  vv ##a## b## vv dd ",
		 "#define macro(a, b, c) vv ## @0:a ## @1:b ## vv dd "},
		{"#define macro(a,b,c)  vv #### b## vv dd ",
		 "#define macro(a, b, c) vv ## @1:b ## vv dd "},
		{"#define macro(a,b,...)  vv #### b## __VA_ARGS__ vv dd ",
		 "#define macro(a, b, ...) vv ## @1:b ## VA_ARGS vv dd "},
		{"#define macro(a,b...)  vv #### b## __VA_ARGS__ vv dd ",
		 "#define macro(a, b...) vv ## @1:b ## VA_ARGS vv dd "},
	};

	for(int i = 0; i < sizeof(test_macro_string)/sizeof(test_macro_string[0]); i++) {
		tokenize_from_string(test_macro_string[i].sample);
		macro_t *pma = vector_top(&macro_buffer);
		UNIT_TEST_STR_EQUAL(macro_format(pma), test_macro_string[i].ans);
	}


	const char *ss[] = {
		"\"Hello World!\"",
		"\"prefix\"\"\\n\\r\\t\\\\suffix\"",
		"\"prefix\" \r\n  \t  \"suffix\"",
		"\"pre\\\"fix\"  \t\n \"suf\\\"fix\"",
		"\"\\x48\\x65\\x6c\\x6c\\x6f\\x20\\x57\\x6f\\x72\\x6c\\x64\\x21\"",
		"\"\\0110\\0145\\0154\\0154\\0157\\040\\0127\\0157\\0162\\0154\\0144\\041\""
	};
	const char *ans[] = {
		"Hello World!",
		"prefix\n\r\t\\suffix",
		"prefixsuffix",
		"pre\"fixsuf\"fix",
		"Hello World!",
		"Hello World!"
	};

	int test_len = sizeof(ss)/sizeof(ss[0]);
	for(int i = 0; i < test_len; i++)
	{
		char* p = register_string(ss[i]);
		UNIT_TEST_ASSERT(strcmp(p, ans[i]) == 0, "fail at case #%d, should be '%s' but got '%s'.", i, ans[i], p);
	}

	const char *ns[] = {
		"12345678", "98765432", "87654321", "7654321",
		"7fa", "6ffaewr",
	};

	const int nas[] = {
		01234567, 12345678, 0x12345678,
		00, 98765432, 0x98765432,
		00, 87654321, 0x87654321,
		07654321, 7654321, 0x7654321,
		07, 7, 0x7fa,
		06, 6, 0x6ffae,
	};

	for(int i = 0; i < sizeof(ns)/sizeof(ns[0]); i++) {
		char *p = (char *)ns[i];
		int a = next_number(&p, 8);
		UNIT_TEST_ASSERT(a == nas[3 * i], "fail at case #%d, oct, should be %d but got %d.", i, nas[3 * i], a);
		p = (char *)ns[i];
		a = next_number(&p, 10);
		UNIT_TEST_ASSERT(a == nas[3 * i + 1], "fail at case #%d, dec, should be %d but got %d.", i, nas[3 * i + 1], a);
		p = (char *)ns[i];
		a = next_number(&p, 16);
		UNIT_TEST_ASSERT(a == nas[3 * i + 2], "fail at case #%d, hex, should be %d but got %d.", i, nas[3 * i + 2], a);
	}

	UNIT_TEST_END;
#endif
	return 0;
}

